name: anjuman_e_najmi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  # flutter splash 
  flutter_native_splash: ^2.2.19
  # flutter toast
  fluttertoast: ^8.2.1
  #  google font
  #google_fonts: ^4.0.4
  #  state management
  flutter_bloc: ^8.1.2
  #  otp textfield
  pin_code_fields: ^7.4.0
  #  app launch icon
  flutter_launcher_icons: ^0.13.1
   #  internet connection checker
  internet_connection_checker: ^1.0.0+1
  connectivity: ^3.0.6
  #imagepicker
  image_picker: ^0.8.7+5
  http: ^0.13.6 
  shared_preferences: ^2.2.0
  syncfusion_flutter_pdfviewer:
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#3454A7"
  image: assets/new_logo.png
  android_disable_fullscreen: true
#flutter_launcher_icons:
 # android: "launcher_icon"
 # ios: true
  #remove_alpha_ios: true
 # image_path: "assets/new_logo.png"

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Font/Helvetica.ttf
